name = "ezra"
type = "javascript"

zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-01-07"

kv_namespaces = [ 
  { binding = "SESSIONS_KV", id = "bae6074d66fe4ac9bb441aebb1a559bc" }
]

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format="service-worker"

# [secrets]
# SUPABASE_PROJECT_URL
# SUPABASE_PROJECT_ANON_KEY
# COOKIE_SECRET